services:
    crocos_security.context:
        class: Crocos\SecurityBundle\Security\SecurityContext
        calls:
            - [ setPreviousUrlHolder, [ @crocos_security.previous_url_holder ] ]

    crocos_security.checker:
        class: Crocos\SecurityBundle\Security\AuthChecker
        arguments:
            - @crocos_security.annotation_loader
            - @crocos_security.forwarding_controller_matcher

    crocos_security.annotation_loader:
        class: Crocos\SecurityBundle\Security\AnnotationLoader
        arguments:
            - @annotation_reader
            - @crocos_security.auth_logic_resolver
            - @crocos_security.role_manager_resolver
            - @crocos_security.http_auth_factory

    crocos_security.forwarding_controller_matcher:
        class: Crocos\SecurityBundle\Security\ForwardingControllerMatcher
        arguments:
            - @controller_name_converter

    crocos_security.previous_url_holder:
        class: Crocos\SecurityBundle\Security\PreviousUrlHolder
        arguments:
            - @session

    crocos_security.auth_logic_resolver:
        class: Crocos\SecurityBundle\Security\AuthLogic\AuthLogicResolver

    crocos_security.auth_logic.session:
        class: Crocos\SecurityBundle\Security\AuthLogic\SessionAuth
        arguments:
            - @session
        tags:
            - { name: crocos_security.auth_logic, alias: session }

    crocos_security.http_auth_factory:
        class: Crocos\SecurityBundle\Security\HttpAuth\HttpAuthFactory

    crocos_security.role_manager_resolver:
        class: Crocos\SecurityBundle\Security\Role\RoleManagerResolver

    crocos_security.role_manager.session:
        class: Crocos\SecurityBundle\Security\Role\SessionRoleManager
        arguments:
            - @session
        tags:
            - { name: crocos_security.role_manager, alias: session }

    crocos_security.role_manager.in_memory:
        class: Crocos\SecurityBundle\Security\Role\InMemoryRoleManager
        tags:
            - { name: crocos_security.role_manager, alias: in_memory }
